# Undertow
server:
    port: 8008
    undertow:
        accesslog:
          dir:  # Undertow access log directory.
          enabled: false  # Enable access log.
          pattern: common   # Format pattern for access logs.
          prefix: access_log  # Log file name prefix.
          rotate: true  # Enable access log rotation.
          suffix: log   # Log file name suffix.
        buffer-size:  # Size of each buffer in bytes.
        direct-buffers:   # Allocate buffers outside the Java heap.
        io-threads:   # Number of I/O threads to create for the worker.
        max-http-post-size: 0  # Maximum size in bytes of the HTTP post content.
        worker-threads:   # Number of worker threads.

spring:
  application:
      name: dandelion-upm
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  resources:
    static-locations: classpath:/static/,classpath:/views/,classpath:/doc/
  main:
    allow-bean-definition-overriding: true


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.icepear.dandelion.upm.**.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置
      logic-delete-value: -1
      logic-not-delete-value: 0
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  type-enums-package: cn.icepear.dandelion.upm.**.enums
dubbo:
  scan:
    base-packages: cn.icepear.dandelion.upm.api.remote
  application:
    name: dandelion-upm
  protocol:
    name: dubbo
    port: 18008
  registry:
    address: N/A
security:
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: hos
      client-secret: hos
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
      prefer-token-info: true
